import type { Metadata } from "next";
import Link from "next/link";
import DotGridBackground from "@/components/shared/DotGridBackground";
import CoinMark from "@/components/shared/CoinMark";

/**
 * Terms of Service stub. Boilerplate prepared for Digistore marketplace
 * approval review. Real legal copy + governing-state choice + last-
 * updated date need David's + counsel's sign-off before production
 * push. Placeholder markers in square brackets must be filled in.
 */

export const metadata: Metadata = {
  title: "Terms — loot.works",
  description: "Terms of Service for the loot.works platform.",
  robots: { index: false, follow: false },
};

export default function TermsPage() {
  return (
    <main className="relative min-h-[100dvh] bg-[var(--bg-page)] overflow-hidden">
      <DotGridBackground />

      <div className="relative z-10 max-w-2xl mx-auto px-6 py-16">
        <Link
          href="/"
          className="inline-flex items-center gap-2 mb-12 text-[var(--text-muted)] hover:text-[var(--text-primary)] transition"
        >
          <CoinMark size={22} color="#5CE0B8" />
          <span
            className="text-sm font-[600] tracking-[0.06em]"
            style={{ fontFamily: "var(--font-label)", color: "#5CE0B8" }}
          >
            LOOT.WORKS
          </span>
        </Link>

        <h1
          className="text-[32px] leading-tight font-[600] text-[var(--text-primary)] mb-3"
          style={{ fontFamily: "var(--font-body)" }}
        >
          Terms of Service
        </h1>
        <div
          className="text-[11px] font-[500] tracking-[0.12em] uppercase text-[var(--text-muted)] mb-10"
          style={{ fontFamily: "var(--font-label)" }}
        >
          Last updated: May 23, 2026
        </div>

        <Prose>
          <P>
            These Terms govern your use of loot.works (the
            &ldquo;Service&rdquo;), operated by TruConnect (&ldquo;we&rdquo;,
            &ldquo;us&rdquo;). By creating an account or subscribing you agree
            to these Terms.
          </P>

          <H2>1. Acceptance</H2>
          <P>
            You must be at least 18 years old or the age of majority in your
            jurisdiction. By using the Service you confirm you meet this
            requirement and agree to be bound by these Terms.
          </P>

          <H2>2. The Service</H2>
          <P>
            loot.works is an AI-assisted reseller tool. Features include barcode
            and image-based item scanning, resale price estimation, condition
            grading, listing generation, deal feeds, and watch-list alerts.
            Estimates are generated by AI from publicly available pricing
            patterns and your inputs &mdash; they are not guarantees and not
            financial or investment advice.
          </P>

          <H2>3. Subscriptions and billing</H2>
          <UL>
            <LI>Pro is offered as a $14.99/month or $99.99/year subscription.</LI>
            <LI>Subscriptions auto-renew until cancelled.</LI>
            <LI>If you purchased through our Stripe checkout, you can manage or cancel from Account &rarr; Manage plan, which opens the Stripe Customer Portal.</LI>
            <LI>If you purchased through a Digistore24 affiliate link, you can manage or cancel via Digistore24&rsquo;s order portal. The Account page links you there directly.</LI>
            <LI>Prices are in USD and subject to change with at least 30 days&rsquo; notice for existing subscribers.</LI>
          </UL>

          <H2>4. Refunds</H2>
          <P>
            Purchases made through Digistore24 are covered by Digistore24&rsquo;s
            60-day money-back guarantee. Submit refund requests through
            Digistore24&rsquo;s order-management portal within 60 days of
            purchase. Stripe purchases are covered by the same 60-day
            money-back guarantee; contact us within 60 days of purchase to
            request a full refund.
          </P>

          <H2>5. User conduct</H2>
          <P>You agree not to:</P>
          <UL>
            <LI>Use the Service for any unlawful purpose, including reselling counterfeit goods.</LI>
            <LI>Reverse-engineer, scrape, or attempt to extract our data, models, or proprietary algorithms.</LI>
            <LI>Share your account credentials or sublicense access.</LI>
            <LI>Use automated systems to flood the Service with requests beyond normal interactive use.</LI>
            <LI>Submit content that infringes others&rsquo; rights or violates applicable law.</LI>
          </UL>

          <H2>6. Intellectual property</H2>
          <P>
            The Service, including its branding, design, code, and AI
            integrations, is owned by us or our licensors. You receive a limited,
            non-exclusive, non-transferable license to use the Service for its
            intended purpose during your subscription. You retain ownership of
            content you submit (scans, photos, notes) and grant us a license to
            process it to deliver the Service and to retain anonymized aggregate
            data for pricing accuracy.
          </P>

          <H2>7. Disclaimers</H2>
          <P>
            The Service is provided &ldquo;as is&rdquo; without warranties of
            any kind. Resale price estimates, condition grades, and listing
            suggestions are informational only. We do not guarantee any item
            will sell, will sell at the estimated price, or will be profitable.
            You are solely responsible for your purchase, listing, and resale
            decisions and for compliance with applicable laws (sales tax, income
            reporting, platform rules).
          </P>

          <H2>8. Limitation of liability</H2>
          <P>
            To the maximum extent permitted by law, our total liability for any
            claim arising from your use of the Service is limited to the
            amounts you paid us in the 12 months before the claim. We are not
            liable for indirect, incidental, consequential, or lost-profit
            damages.
          </P>

          <H2>9. Termination</H2>
          <P>
            You may cancel your subscription at any time through the channels in
            Section 3. We may suspend or terminate your account for breach of
            these Terms or for misuse of the Service.
          </P>

          <H2>10. Governing law</H2>
          <P>
            These Terms are governed by the laws of Georgia, without regard to
            conflict-of-law principles. Disputes will be resolved in the state
            or federal courts located in Georgia.
          </P>

          <H2>11. Changes to these Terms</H2>
          <P>
            We may update these Terms. Material changes will be announced
            in-app or by email at least 14 days before taking effect. Continued
            use of the Service after that date constitutes acceptance.
          </P>

          <H2>12. Contact</H2>
          <P>
            Questions: <Mail>lootworks.goflip@gmail.com</Mail>.
            <br />
            Operated by TruConnect.
          </P>
        </Prose>

        <FooterBar />
      </div>
    </main>
  );
}

// ── Typography helpers — mirror /privacy. Keep them in sync if you
//    add styles to one.

function Prose({ children }: { children: React.ReactNode }) {
  return (
    <div
      className="space-y-5 text-[var(--text-primary)]"
      style={{ fontFamily: "var(--font-body)" }}
    >
      {children}
    </div>
  );
}

function H2({ children }: { children: React.ReactNode }) {
  return (
    <h2
      className="text-lg font-[600] text-[var(--text-primary)] pt-4"
      style={{ fontFamily: "var(--font-body)" }}
    >
      {children}
    </h2>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <p
      className="text-sm font-[300] leading-relaxed text-[var(--text-primary)]/85"
      style={{ fontFamily: "var(--font-body)" }}
    >
      {children}
    </p>
  );
}

function UL({ children }: { children: React.ReactNode }) {
  return (
    <ul className="space-y-2 list-disc pl-5 text-sm font-[300] leading-relaxed text-[var(--text-primary)]/85">
      {children}
    </ul>
  );
}

function LI({ children }: { children: React.ReactNode }) {
  return <li>{children}</li>;
}

function Mail({ children }: { children: React.ReactNode }) {
  return (
    <a
      href={`mailto:${children}`}
      className="text-[var(--money)] hover:underline"
    >
      {children}
    </a>
  );
}

function FooterBar() {
  return (
    <div
      className="mt-16 pt-6 border-t border-white/[0.04] flex items-center justify-center gap-3 text-[10px] tracking-[0.12em] uppercase"
      style={{ fontFamily: "var(--font-label)" }}
    >
      <Link
        href="/privacy"
        className="text-white/40 hover:text-white/70 transition"
      >
        Privacy
      </Link>
      <span className="text-white/20">·</span>
      <Link
        href="/terms"
        className="text-white/40 hover:text-white/70 transition"
      >
        Terms
      </Link>
      <span className="text-white/20">·</span>
      <span className="text-white/40">&copy; 2026 loot.works</span>
    </div>
  );
}
